### ISSUE TITLE
DllNotFoundException: openvr_api

### ISSUE THREAD

**Issue by Spaxe** [B-Reel/vr-weight#1]
This is a newbie error, and I apologise in advance for opening an issue. I can't find an answer on Steam forums, so you might know.

After downloading the Unity project, I opened it up in Unity 5.3.5f1 personal, accepting recommended defaults that Unity suggests.

When I tried to run it, this is the error I get:

```
DllNotFoundException: openvr_api
Valve.VR.OpenVR.GetInitToken () (at Assets/Plugins/openvr_api.cs:3402)
Valve.VR.OpenVR+COpenVRContext.CheckClear () (at Assets/Plugins/openvr_api.cs:3556)
Valve.VR.OpenVR+COpenVRContext.VRSystem () (at Assets/Plugins/openvr_api.cs:3565)
Valve.VR.OpenVR.get_System () (at Assets/Plugins/openvr_api.cs:3702)
ChangeScene.Update () (at Assets/Scripts/ChangeScene.cs:22)
```

Why is that?

**Comment by lucasdupin** [comment]
Hey,
You'll need Unity 5.4+, you can get it from here:
https://unity3d.com/unity/beta

Let me know if it fixes your error, otherwise just reopen the issue ;-)

**Comment by perqa** [comment]
I get the same thing with Unity 5.4.1
`
DllNotFoundException: openvr_api
Valve.VR.OpenVR.GetInitToken () (at Assets/SteamVR/Plugins/openvr_api.cs:4014)
Valve.VR.OpenVR+COpenVRContext.CheckClear () (at Assets/SteamVR/Plugins/openvr_api.cs:4190)
Valve.VR.OpenVR+COpenVRContext.VRSystem () (at Assets/SteamVR/Plugins/openvr_api.cs:4199)
Valve.VR.OpenVR.get_System () (at Assets/SteamVR/Plugins/openvr_api.cs:4364)
SteamVR_ControllerManager.Refresh () (at Assets/SteamVR/Scripts/SteamVR_ControllerManager.cs:187)
SteamVR_ControllerManager.OnTrackedDeviceRoleChanged (System.Object[] args) (at Assets/SteamVR/Scripts/SteamVR_ControllerManager.cs:158)
SteamVR_ControllerManager.OnEnable () (at Assets/SteamVR/Scripts/SteamVR_ControllerManager.cs:50)
UnityEngine.Object:Instantiate(GameObject)
SteamVR_Render:Awake() (at Assets/SteamVR/Scripts/SteamVR_Render.cs:306)
`

**Comment by lookbothways** [comment]
Same here - any suggestions would be a great help.

**Comment by lucasdupin** [comment]
Have you tried to remove and add SteamVr again?
It looks like Unity can't find the plugin.

The project was built for the Vive.

**Comment by austinmao** [comment]
I am seeing this same issue on OS X with Unity 5.5.0f3 (64 bit) on OpenGL 4.1 and SteamVR plugin 1.1.0. When I start a blank project and add the SteamVR [CameraRig] prefab, I get this error when hitting Play;

Like the others, I'm trying to develop on a Macbook while roaming.

FYI this is likely a bug with SteamVR

**Comment by lucasdupin** [comment]
Yep, 
And I don't think you'll be able to develop on a Mac, take a look at this link:

https://steamcommunity.com/app/358040/discussions/0/392183857619760099/
